"""create bot_config and add prefix

Revision ID: f12d0814fce3
Revises: 
Create Date: 2025-09-20 15:45:50.827071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12d0814fce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_index(op.f('ix_bot_config_config_key'), 'bot_config', ['config_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_config_config_key'), table_name='bot_config')
    op.drop_table('bot_config')
    # ### end Alembic commands ###
